"""initial

Revision ID: a47ef0cd1520
Revises:
Create Date: 2026-03-14 23:36:19.494885

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a47ef0cd1520"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("place_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("status", sa.Enum("ONLINE", "OFFLINE", name="devicestatusenum"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_devices_place_id"), "devices", ["place_id"], unique=False)
    op.create_table(
        "mqtt_credentials",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("allowed_place_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(
        op.f("ix_mqtt_credentials_user_id"), "mqtt_credentials", ["user_id"], unique=False
    )
    op.create_table(
        "actuators",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "value_type",
            sa.Enum("NUMBER", "BOOLEAN", "ENUM", name="actuatorvaluetypeenum"),
            nullable=False,
        ),
        sa.Column("unit_label", sa.String(length=50), nullable=False),
        sa.Column("precision", sa.Integer(), nullable=False),
        sa.Column("min_value", sa.Float(), nullable=True),
        sa.Column("max_value", sa.Float(), nullable=True),
        sa.Column("step", sa.Float(), nullable=True),
        sa.Column("enum_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "key"),
    )
    op.create_table(
        "sensors",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("value_type", sa.Enum("NUMBER", "BOOLEAN", name="valuetypeenum"), nullable=False),
        sa.Column("unit_label", sa.String(length=50), nullable=False),
        sa.Column("precision", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "key"),
    )
    op.create_table(
        "sensor_thresholds",
        sa.Column("sensor_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Enum("MIN", "MAX", name="thresholdtypeenum"), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column(
            "severity", sa.Enum("WARNING", "CRITICAL", name="thresholdseverityenum"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["sensor_id"], ["sensors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sensor_thresholds")
    op.drop_table("sensors")
    op.drop_table("actuators")
    op.drop_index(op.f("ix_mqtt_credentials_user_id"), table_name="mqtt_credentials")
    op.drop_table("mqtt_credentials")
    op.drop_index(op.f("ix_devices_place_id"), table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
